title: Alayna Nicholson
description: OMSCS @ Georgia Tech | BSChBE @ Georgia Tech | Correlation One Fellowship Member | Sr. Marketing Analyst @ Ace Hardware
theme: jekyll-theme-minimal
logo: /assets/img/headshot2.jpg
linkedin_username: alaynanicholson
